version: "3.8"
services:

  redis:
    image: redis:latest


  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "redis-commander"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  producer:
    image: producer:latest
    build: .
    command: python producer.py --debug
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    deploy:
      replicas: 3


  consumer:
    image: consumer:latest
    build: .
    command: python consumer.py --debug
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    deploy:
      replicas: 6
